### ISSUE TITLE
Transition ownership of whenever-elasticbeanstalk project

### ISSUE THREAD

**Issue by jufemaiz** [dignoe/whenever-elasticbeanstalk#13]
Hi @dignoe - any interest in transferring ownership of this project?
Cheers, Joel

**Comment by dignoe** [comment]
Yep! I don't use elasticbeanstalk anymore, so I'd be glad to do that.

**Comment by jufemaiz** [comment]
Thanks mate! Just out of interest, what have you headed to now?
