### ISSUE TITLE
create_cron_leader - Set instance_id to /var/app/support/instance_id - When file doesn't exist

### ISSUE THREAD

**Issue by sushmasatish** [dignoe/whenever-elasticbeanstalk#15]
I have a single elastic-beanstalk instance which I created just 2 days back: 29-Jul-2014 which didn't have /var/app/support directory. And Hence I got errors: 

whenever-elasticbeanstalk-1.1.3/bin/create_cron_leader:
36:in `initialize': No such file or directory - /var/app/support/instance_id (Errno::ENOENT)
        from /usr/local/share/ruby/gems/2.0/gems/whenever-elasticbeanstalk-1.1.3/bin/create_cron_leader:36:in`open'

As per code in the else block, the code assumes that a support directory exists, Can a fix be added to check whether support directory exists or not, if not, then create the directory and then do File.open?

**Comment by jufemaiz** [comment]
Hi @sushmasatish - this issue is known and has been resolved at https://github.com/jufemaiz/whenever-beanstalk 

I've still got to get authority over at rubygems for access :)

**Comment by jufemaiz** [comment]
In the interim you can use the following in your Gemfile:

```
gem 'whenever-elasticbeanstalk', :git => 'https://github.com/dignoe/whenever-elasticbeanstalk.git', :ref => '6a3b58a'
```

Can you confirm if this solves your issue.

**Comment by jufemaiz** [comment]
Gem v1.1.4 released.

https://rubygems.org/gems/whenever-elasticbeanstalk

**Comment by sushmasatish** [comment]
Tried with v1.1.4, But getting 

AWS::EC2::Errors::UnauthorizedOperation: You are not authorized to perform this operation.

in create_cron_leader file - line 49:
env_name = ec2.instances[instance_id].tags["elasticbeanstalk:environment-name"]

Have got both AWS_ACCESS_KEY_ID and AWS_SECRET_KEY set in configuration.

**Comment by jufemaiz** [comment]
Hi @sushmasatish, I shifted off the AWS access / secret key method to use EC2 Instance IAM Role Permissions for security's sake ( https://github.com/dignoe/whenever-elasticbeanstalk#ec2-instance-iam-role-permissions )

Can you try again with that noted? Cheers!

**Comment by jufemaiz** [comment]
I'll close this issue if there's no response in 10 days.
