### ISSUE TITLE
Not working with aws-sdk 1.15.0

### ISSUE THREAD

**Issue by j-mcnally** [dignoe/whenever-elasticbeanstalk#4]
/var/app/ondeck/vendor/bundle/gems/aws-sdk-1.15.0/lib/aws/core.rb:474:in `config': undefined method`empty?' for nil:NilClass (NoMethodError)
    from /var/app/ondeck/vendor/bundle/gems/whenever-elasticbeanstalk-1.1.3/bin/create_cron_leader:41:in `<top (required)>'
    from /var/app/ondeck/vendor/bundle/bin/create_cron_leader:23:in`load'
    from /var/app/ondeck/vendor/bundle/bin/create_cron_leader:23:in `<main>'

2013-08-18 21:01:20,581 [ERROR] Error encountered during build of postbuild_0_tourpedo_git_d96cbe5a203408a58aa3d714ab8bdf15d97e8a5a_1376859281475__ebextensions_cron_config: Command cron_01_set_leader failed
Traceback (most recent call last):

Getting this in my logs when i try to deploy. Amazon seems to break a bunch of stuff everytime they put out a new gem :/

**Comment by dignoe** [comment]
Do you have your `config/whenever-elasticbeanstalk.yml` file setup correctly and are using the corresponding RAILS_ENV environment variable?

**Comment by j-mcnally** [comment]
thats a valid point, ill double check.

**Comment by j-mcnally** [comment]
i am almost sure i missed that step :+1:
