### ISSUE TITLE
 whenever-elasticbeanstalk.yml does not read  from ERB environment variables

### ISSUE THREAD

**Issue by nikhilvs** [dignoe/whenever-elasticbeanstalk#7]
When we use elastic-beanstalk, it is advised to load access key and secret key from software configuration.

When we hard code access key and secret key in  whenever-elasticbeanstalk.yml, application works. But with erb environment variables, elasticbeanstalk gives following error :
[Instance: xxxxxxx Module: AWSEBAutoScalingGroup ConfigSet: null] Command failed on instance. Return code: 1 Output: Error occurred during build: Command cron_01_set_leader failed .

**Comment by jufemaiz** [comment]
https://github.com/dignoe/whenever-elasticbeanstalk/pull/11
