### ISSUE TITLE
Doesn't work with latest elasticbeanstalk

### ISSUE THREAD

**Issue by ygee07** [dignoe/whenever-elasticbeanstalk#8]
Some folders have been renamed and moved in the latest elasticbeanstalk, so it fails to run some scripts starting with cron_01_set_leader

**Comment by dignoe** [comment]
I'm no longer using elasticbeanstalk, so I'm not actively maintaining this code anymore. If someone has a working fork, I can direct people there and give them access to maintain the gem.

**Comment by ygee07** [comment]
Thanks, I'll try to work on a fork then.

**Comment by jufemaiz** [comment]
Hi @dignoe I believe mine is…

https://github.com/dignoe/whenever-elasticbeanstalk/pull/10

**Comment by jufemaiz** [comment]
@greyder can you test + confirm my master branch before I merge. Just want to ensure others do not have problems.

**Comment by jufemaiz** [comment]
```
gem 'whenever-elasticbeanstalk', :git => 'https://github.com/dignoe/whenever-elasticbeanstalk.git', :ref => '6a3b58a'
```

Please confirm if you are still using this @greyder

**Comment by jufemaiz** [comment]
Gem v1.1.4 released.

https://rubygems.org/gems/whenever-elasticbeanstalk

Also @greyder I'm planning on closing this in 7 days if no response.

Cheers.

**Comment by ygee07** [comment]
Hi @jufemaiz, sorry for the delayed response. I have already found an alternative to Whenever, so I can't test it on our side that easily now. Glad you're reviving it though, might use it again in the near future. 

Best Regards :)

**Comment by jufemaiz** [comment]
Thanks for the feedback @greyder 

Could you provide details of the alternative for potential users?

Cheers!

**Comment by ygee07** [comment]
I've setup Sidekiq for background tasks instead :)
